/** Steps in the onboarding flow, in the order the user moves through them. */
export type Step =
  | 'personal-info'
  | 'account'
  | 'sending-code'
  | 'verify-code'
  | 'welcome'
  | 'role'
  | 'job'
  | 'photo-upload'
  | 'photo-uploaded'
  | 'org-type'
  | 'org-details'
  | 'company-settings'
  | 'done'
